### ISSUE TITLE
Windows Phone 8.1 support

### ISSUE THREAD

**Issue by JohnMcLear** [randdusing/cordova-plugin-bluetoothle#24] opened 2014-04-03 12:10 UTC
Premature but getting it in here mostly for @donc to see:

"With Windows Phone 8.1, we are adding a wide array of new features including support for Bluetooth LE to connect to devices" -- http://blogs.windows.com/windows/b/buildingapps/archive/2014/04/02/extending-platform-commonality-through-universal-windows-apps.aspx

**Comment by fritsjan** [comment] 2015-01-19 18:00
Is this easy to port to windows 8 app support? (the desktop that is) 
I need btle support for desktop as well.

**Comment by randdusing** [comment] 2015-01-19 22:14
I just started working on the Windows support a few days ago. Setting up a good dev environment has been painful with a Macbook. I believe Windows 8.1 Phone / Desktop / Browser all use the same code, but it should be easy to port if not.

**Comment by fritsjan** [comment] 2015-01-20 08:36
That is good news. I am planning on working with this soon. Can you give me a heads up on your progress?

**Comment by randdusing** [comment] 2015-01-20 21:22
Sure, I can post an update every few days. I'm putting aside most of my other projects for now. But I'm also in New Zealand... bad wifi and plenty of outdoor activities to take up my time. :)

**Comment by fritsjan** [comment] 2015-01-20 21:32
Well, in the end it is about enjoying life! So enjoy the outdoors! 

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [BluetoothLE] Windows Phone 8.1 support (#24)
Van: Rand Dusing <notifications@github.com>
Aan: randdusing/BluetoothLE <BluetoothLE@noreply.github.com>
Cc: Frits Jan van Kempen <mail@fritsjan.nl>

**Comment by chemazeman** [comment] 2015-01-21 07:38
thx. I look forward to the first lines of code to try windows. you have a good stay in New Zealand and do not forget us;)

**Comment by randdusing** [comment] 2015-01-22 04:21
Anyone familiar with debugging Windows Phone 8.1 apps? I'm unable to get weinre working. I was planning to do most testing in a "regular" Windows 8.1 app, but some of the necessary classes are only available in Windows Phone 8.1.

**Comment by randdusing** [comment] 2015-01-22 08:52
Assuming I get weinre working, it looks like it won't help that much with debugging besides console.log output. Without Visual Studio support for debugging Windows Phone 8.1 Cordova apps, progress will be very slow, and thus I'll probably wait until Visual Studio 2015 comes out, which I believe will fully support this.

**Comment by diverJohn** [comment] 2015-02-05 17:22
Can you provide an estimated date for Windows Phone 8.1 Phonegap Build support?  Thanks...

**Comment by randdusing** [comment] 2015-02-07 17:02
I'm going to take another look in the coming weeks based on the information @MiBLE provided, but I can't give much of an estimate.

**Comment by quilkin** [comment] 2015-02-25 00:07
I can't find @MiBLE 's input, but VS2013 now has a plugin for Cordova which I am  using for Android. I have added com.randdusing,blutoothle as a custom plugin (which was accepted) but:
a) on Android emulator  I get 'Uncaught ReferenceError: bluetoothle is not defined' ;
b) on iOS emulator it goes further but then get  'missing exec:BluetoothLePlugin.initialize'
This is using VS2013 on Windows7; I don't (yet) have a Windows8.1 machine so can't emulate for that.
Don't know if any of this is useful; as you say may be better to wait for VS2015. I'm looking forward to being able to use Cordova/BTle on Microsoft Surface 3 at some stage, so will be interested to see your developments..

**Comment by randdusing** [comment] 2015-02-26 19:21
Check out #129 for @MiBLE 's input. 

For the issue, did you declare var bluetoothle within your index.js? If that doesn't work, see if my example app works. You just need to copy the www folder and add the console.log and bluetoothle plugins.

**Comment by quilkin** [comment] 2015-02-28 08:29
Thanks for #129 link. That looks promising.
The issue is only occurring with the VS2013 Cordova plugin. Everything works (with Android & iOS) if I use the Cordova CLI without the plugin. For Windows Cordova apps I've now found there seem to be other documented issues e.g. around expired certificates, so I'll wait until that's been sorted.

**Comment by randdusing** [comment] 2016-03-24 17:27
Windows platform has recently been updated to bring it more in line with Android and iOS. I'll also be ordering a Surface Pro in the next few days, so I'll be able to help address any bugs that popup.

**Closed by randdusing** 2016-03-24 17:27 UTC
Labels: enhancement
